import datetime
print(datetime.datetime.now())
print(datetime.datetime.now().date())
print(datetime.datetime.now().time())
print(datetime.datetime.now().ctime())
print(datetime.datetime.now().day)
print(datetime.datetime.now().isoweekday())
print(datetime.datetime.now().month)
print(datetime.datetime.now().year)
print(datetime.datetime.now().fromisocalendar(2021,4,4))
print(datetime.datetime.now().hour)
print(datetime.datetime.now().minute)
print(datetime.datetime.now().second)
print(datetime.datetime.now().today())
